CREATE TABLE IF NOT EXISTS posts (
	id TEXT PRIMARY KEY NOT NULL,
	community TEXT NOT NULL,
   	poster TEXT NOT NULL,
	content TEXT NOT NULL,
	emotion INTEGER DEFAULT 0,
	spoiler INTEGER DEFAULT 0,
	timestamp TEXT DEFAULT CURRENT_TIMESTAMP
)